export const dataList = [
  { title: "Age of Empires", genre: "action", state: "available" },
  { title: "Acceptence", genre: "action", state: "patching" },
  { title: "Account", genre: "shooters", state: "available" },
  { title: "Backbone", genre: "rpg", state: "patching" },
  { title: "Access", genre: "racing", state: "available" },
  { title: "Age of Conan", genre: "racing", state: "maintenance" },
  { title: "Accurate", genre: "sports", state: "available" },
  { title: "About", genre: "action", state: "patching" },
  { title: "Age of World", genre: "shooters", state: "available" },
  { title: "Baby", genre: "rpg", state: "patching" },
  { title: "Eagle", genre: "open world", state: "maintenance" },
  { title: "Balance", genre: "simulation", state: "available" },
  { title: "Calculation", genre: "sports", state: "available" },
  { title: "Call", genre: "adventure", state: "patching" },
  { title: "Cage", genre: "shooters", state: "available" },
  { title: "Dafts", genre: "casual", state: "maintenance" },
  { title: "Dada", genre: "demo", state: "available" },
  { title: "Habitat", genre: "battale royale", state: "available" },
  { title: "Dabs", genre: "sports", state: "available" },
  { title: "Facedown", genre: "shooters", state: "available" },
  { title: "Cage", genre: "shooters", state: "available" },
  { title: "Abandon", genre: "rpg", state: "patching" },
  { title: "Facelift", genre: "racing", state: "available" },
  { title: "Dafts", genre: "horror", state: "maintenance" },
  { title: "Gagbart", genre: "simulation", state: "available" },
  { title: "Galba", genre: "platformer", state: "available" },
  { title: "Dabs", genre: "sports", state: "available" },
];
